global using Microsoft.AspNetCore.Identity;
global using HospitalManagementSystem.Application.Models.User;
global using HospitalManagementSystem.Core.Entities;
global using HospitalManagementSystem.Application.Models.Patients;
global using HospitalManagementSystem.DataAccess;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using HospitalManagementSystem.Application.Services;
global using HospitalManagementSystem.Application.Services.IServices;
global using HospitalManagementSystem.DataAccess.Persistence;
global using Microsoft.AspNetCore.Identity.UI.Services;
global using Microsoft.EntityFrameworkCore;
global using HospitalManagementSystem.Application.Models.Account;
global using HospitalManagementSystem.Models;
global using System.Diagnostics;
global using System.Security.Claims;
global using HospitalManagementSystem.Application.Models.Appointments;
global using HospitalManagementSystem.Application.Models.Doctors;
global using using HospitalManagementSystem.Application.Models.Nurses;
;

